### ISSUE TITLE
Please add Readme, Licence and Copyright

### ISSUE THREAD

**Issue by riedel** [sdsc-bw/DataFactory#1]
Copyright note should be in each file.

**Comment by HuangYiran** [comment]
Which license is advised to take? Is MIT too liberal?

**Comment by DrMartinHeck** [comment]
Just to give my opinion:
I think a liberal licence is good as long as it is compatible with having the data here.

**Comment by DrMartinHeck** [comment]
I assign this to Yiran, as I think MIT licence is now the default.
